### ISSUE TITLE
Not able to jodel

### ISSUE THREAD

**Issue by No3x** [krokofant/JodelXposed#20]
Hi, I'm not able to post jodel at all. 
I'm using version 4.12.5 currently as it is the latest known version jodel starts at all.

Is there another version that JodelXposed is working properly with?

Edit: I read the xda thread and want to add: I mentioned JodelXposed once as I unveiled somebody responding to his own jodel and pretending to be somebody else. This might be the reason for a ban?

**Comment by the-0ther** [comment]
For now the best method is to just uninstall JodelXposed and wait for an update from @krokofant. The latest version of Jodel is usable even if Xposed is installed and you also can see the OP. For location spoofing you have to use an external app. 
Or you can try to get it working with Xprivacy and rootcloak as written in the XDA thread, but for me it didn't work.

**Comment by No3x** [comment]
So it's a know limitation of JodelXposed not able to jodel and reply?

**Comment by krokofant** [comment]
@Unbrick wizardry has fixed this. I'll leave this open until the official release.
