### ISSUE TITLE
Changeable ScaleType on image upload

### ISSUE THREAD

**Issue by krokofant** [krokofant/JodelXposed#27]
Right now there is no way to change the scale type on images shared to Jodel. To avoid the need of editing a photo before posting the scale type could be toggled on the image.

**Comment by Unbrick** [comment]
Maybe add a cropping & scaling activity from a library like: https://github.com/ekimual/croperino

**Comment by krokofant** [comment]
@Unbrick That sounds like a good idea. To include it in the ShareActivity(#42) would be preferable. At first I thought about re-implementing the old method of creating a VolDown listener on the post creation fragment.

**Comment by Unbrick** [comment]
Closed with 947be289c85780eb5aa5ee7b8ad44407cc90d06b
Now available in PhotoEditFragment
