### ISSUE TITLE
Downloader for PostImages

### ISSUE THREAD

**Issue by krokofant** [krokofant/JodelXposed#28]
Add the ability to save images without taking a screenshot

**Comment by Unbrick** [comment]
Any ideas how to trigger the downloading? Double clicking on image or something like that?

**Comment by krokofant** [comment]
I'm working on something that hooks the little menu for every post. Right now it only works on your own image posts and the menu item is not looking so great.

Right now I'm hooking the `com.jodelapp.jodelandroidv3.view.adapter.PostDetailRecyclerAdapter\$\$Lambda\$1`.

And downloading the image via Picasso as it was already a dependency

**Comment by krokofant** [comment]
Downloader is done. What's missing is saving the images to a dedicated folder as unique files.

**Comment by Unbrick** [comment]
Closed with 947be289c85780eb5aa5ee7b8ad44407cc90d06b
Saving now to /sdcard/JodelXposed/saved_images/(currentTimeMillis).jpg
