### ISSUE TITLE
What is needed for the location picker?

### ISSUE THREAD

**Issue by marcelmindemann** [krokofant/JodelXposed#37]
Hi, I am using Android 5.11 with Xposed framework 86, Jodel 4.14.1 and JodelXposed 2.0.0. When trying to pick my location for the location spoofer, JodelXposed force closes. I suspect this is because I am using the microg framework to emulate an installed Play Service. What app/service does JodelXposed use for location picking? 
Also, is it possible to edit the lat and lon manually? When viewing the logcat, I see JodelXposed writing those to some JSON file.

**Comment by krokofant** [comment]
> What app/service does JodelXposed use for location picking? 

We use Leku which demands Google Play Services = 9.4.0

> Also, is it possible to edit the lat and lon manually? When viewing the logcat, I see JodelXposed writing those to some JSON file.

You should be able to edit the `.jodel-settings-v2` and set the `active` field to `true` of the location object and then provide the gps coords in the lat and lng field.

Edit: Note that the file starts with a `.` so you might need to have your file browser show hidden files.

**Comment by marcelmindemann** [comment]
Thanks for your quick answer! Could you please give a quick example of the correct format of the lat and lon values in the .jodel-settings-v2 file? Since I cannot choose a location using the location picker, these values are simply 0 for me.

**Comment by Unbrick** [comment]
It should look like this:

`"location":{"active":true,"lat":52.5200066,"lng":13.404954}` (Berlin)
