### ISSUE TITLE
Migrate to a dedicated JX folder

### ISSUE THREAD

**Issue by krokofant** [krokofant/JodelXposed#38]
The settings file, the shared image and future files related to JX should reside in a dedicated folder on the phone.

**Comment by Unbrick** [comment]
Added

**Comment by krokofant** [comment]
Is it really though? I saw the #39 but I see no changes related to a change of folders.

**Comment by Unbrick** [comment]
Closed with 947be289c85780eb5aa5ee7b8ad44407cc90d06b
