### ISSUE TITLE
Stabilize Beta hooks

### ISSUE THREAD

**Issue by krokofant** [krokofant/JodelXposed#43]
There was a problem where the users opens Jodel and a black screen appears (the Picker most likely) and then goes back to Jodel again in a loop.

This issue have not yet been able to be reproduced by us.

**Comment by DosMike** [comment]
had this after updating on the startup-screen.
cleared cache for jodel and jodel exposed, now it works.

**Comment by krokofant** [comment]
@DosMike Thanks for for input. That seems to make the app start at least for those affected.

**Comment by Unbrick** [comment]
@krokofant @DosMike I guess i have fixed the issue by just simply checking the permissions when opening the picker. Should work now, i'll push it in a sec.

**Comment by timprange** [comment]
I'm having the issue too. After clearing data it is working but only one time. After closing jodel and reopen it, jodel will loop again and I have to clear data again. I checked all permissions they are all enabled.

**Comment by krokofant** [comment]
This seems to be caused by the beta hooks that automatically enabled all beta features. Thus a temporary solution is to inactivate that hook. We'll investigate further to see what can be done to enable the beta hook without these errors.

**Comment by krokofant** [comment]
A selective activation of the beta features might be the solution.

Here are a list of features:
* channels
* hometown
* hashtags
* user_profiling
* hotsorting_new_comment_hot
* hotsorting_loud_comment_new
* hotsorting_hot_comment_new


It would be nice to know what they all do. The first three I recognize.
