### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by agatbox** [krokofant/JodelXposed#56]
can some one walk me trough the install i am kinda dense and did not understand shit

**Comment by krokofant** [comment]
Do you have root and Xposed already? If not you should lookup how to install that on your phone.

**Comment by agatbox** [comment]
okay so i need root how should i root my phone if i dont have windows?

**Comment by krokofant** [comment]
Rooting instructions and such are beyond the scope of this project. I can recommend the XDA forums for instructions but beyond that I can't help.
