### ISSUE TITLE
commenting doesnt work

### ISSUE THREAD

**Issue by code-juggling** [krokofant/JodelXposed#57]
Jodel Version 4.30.2
JodelXposed Version 2.3.0 (Beta)

I'm not able to create a thread or comment on anything.
App crashes after pushing the comment button.

Installed app and your extension today, tried deleting data etc.

Is your extension incompatible with xPrivacy? (thats not a request for making it compatible)

**Comment by Unbrick** [comment]
Can you provide us a StackTrace? 

For me, it works without any problems, but i dont use xPrivacy.

We also don't have added support for xPrivacy.

**Comment by quorn23** [comment]
I'm using xPrivacy and i do not have any issues with the latest JodelXposed/Jodel Combo.

**Comment by Hexaflexagon** [comment]
I have the same Bug and dont use xPrivacy
After pushing the comment button close Jodel without a error.

How can i do a StackTrace?

Android: 6.0.1

Log:
12-22 11:31:44.302 I/Xposed  (24695): Starting JodelXposed
12-22 11:31:44.302 I/Xposed  (24695): Version 2.3.0 (23)
12-22 11:31:44.302 I/Xposed  (24695): JodelTarget 4.30.2 (1000085)
12-22 11:31:44.302 I/Xposed  (24695): JodelLocal 4.31.1 (1000101)
12-22 11:31:44.302 I/Xposed  (24695): ----------
12-22 11:31:44.368 I/Xposed  (24695): JodelXposed: #### Loading hooks ####
12-22 11:31:44.369 I/Xposed  (24695): JodelXposed: #### Acquiring... JodelActivity for snackbar usage ####
12-22 11:31:44.375 I/Xposed  (24695): JodelXposed: #### Acquired JodelActivity for snackbar usage! ####
12-22 11:31:44.375 I/Xposed  (24695): JodelXposed: #### Loading BetaStuff hooks ####
12-22 11:31:44.377 I/Xposed  (24695): JodelXposed: #### BetaStuff hooks loaded! ####
12-22 11:31:44.377 I/Xposed  (24695): JodelXposed: #### Loading ImageStuff hooks ####
12-22 11:31:44.382 I/Xposed  (24695): JodelXposed: #### ImageStuff hooks loaded! ####
12-22 11:31:44.382 I/Xposed  (24695): JodelXposed: #### Loading LocationStuff hooks ####
12-22 11:31:44.383 I/Xposed  (24695): JodelXposed: #### LocationStuff hooks loaded! ####
12-22 11:31:44.383 I/Xposed  (24695): JodelXposed: #### Loading PostStuff hooks ####
12-22 11:31:44.390 I/Xposed  (24695): JodelXposed: #### PostStuff hooks loaded! ####
12-22 11:31:44.390 I/Xposed  (24695): JodelXposed: #### Loading SettingsStuff hooks ####
12-22 11:31:44.392 I/Xposed  (24695): JodelXposed: !!!! FAILED loading SettingsStuff hooks! !!!!
12-22 11:31:44.392 I/Xposed  (24695): 
12-22 11:31:44.392 I/Xposed  (24695): JodelXposed: #### Loading UniqueDeviceIdentifierStuff hooks ####
12-22 11:31:44.395 I/Xposed  (24695): JodelXposed: !!!! FAILED loading UniqueDeviceIdentifierStuff hooks! !!!!
12-22 11:31:44.395 I/Xposed  (24695): 
12-22 11:31:44.395 I/Xposed  (24695): JodelXposed: #### Loading SavePost hooks ####
12-22 11:31:44.397 I/Xposed  (24695): JodelXposed: #### Loading SavePost hooks loaded! ####

**Comment by Unbrick** [comment]
Sorry for the delay, we updated the hooks since then, they shoudn't be a problem anymore. Do you still experience the crashes?

**Comment by li0nsar3c00l** [comment]
Still not working.
Device: Samsung Galaxy S5 with systemless xposed. In case you need other info, hmu

Log:
01-25 23:50:09.025 I/Xposed  (12076): JodelXposed: ----------
01-25 23:50:09.025 I/Xposed  (12076): Starting JodelXposed
01-25 23:50:09.025 I/Xposed  (12076): Version 2.3.0 (23)
01-25 23:50:09.025 I/Xposed  (12076): JodelTarget 4.30.2 (1000085)
01-25 23:50:09.025 I/Xposed  (12076): JodelLocal 4.32.2 (1000202)
01-25 23:50:09.025 I/Xposed  (12076): ----------
01-25 23:50:09.175 I/Xposed  (12076): JodelXposed: #### Loading hooks ####
01-25 23:50:09.175 I/Xposed  (12076): JodelXposed: #### Acquiring... JodelActivity for snackbar usage ####
01-25 23:50:09.195 I/Xposed  (12076): JodelXposed: #### Acquired JodelActivity for snackbar usage! ####
01-25 23:50:09.195 I/Xposed  (12076): JodelXposed: #### Loading BetaStuff hooks ####
01-25 23:50:09.195 I/Xposed  (12076): JodelXposed: #### BetaStuff hooks loaded! ####
01-25 23:50:09.195 I/Xposed  (12076): JodelXposed: #### Loading ImageStuff hooks ####
01-25 23:50:09.205 I/Xposed  (12076): JodelXposed: !!!! FAILED loading ImageStuff hooks! !!!!
01-25 23:50:09.205 I/Xposed  (12076): 
01-25 23:50:09.205 I/Xposed  (12076): JodelXposed: #### Loading LocationStuff hooks ####
01-25 23:50:09.205 I/Xposed  (12076): JodelXposed: #### LocationStuff hooks loaded! ####
01-25 23:50:09.205 I/Xposed  (12076): JodelXposed: #### Loading PostStuff hooks ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### PostStuff hooks loaded! ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### Loading SettingsStuff hooks ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### SettingsStuff hooks loaded! ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### Loading UniqueDeviceIdentifierStuff hooks ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### UniqueDeviceIdentifierStuff hooks loaded! ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### Loading SavePost hooks ####
01-25 23:50:09.215 I/Xposed  (12076): JodelXposed: #### Loading SavePost hooks loaded! ####

**Comment by Unbrick** [comment]
@li0nsar3c00l 
At the moment, the RemoveBlurOnImages changed quite a lot so our implementation isnt working anymore. This leads to a internal crash. 

Thing with jodel is: As soon as an internal crash hasn't been caught, network features are disabled. So commenting won't work. We are currently updating JX to the latest Jodel version (4.32.2). Need to fix a few bugs but should be soon ready to release.

**Comment by Unbrick** [comment]
After the latest update it should work again, could you report back?

**Comment by Unbrick** [comment]
Closing as it should work now. Please create a new issue if you still are encountering problems!
