### ISSUE TITLE
Jodel force close without stacktrace when commenting

### ISSUE THREAD

**Issue by MrYawnie** [krokofant/JodelXposed#59]
Hey, 

For some reason when I try to comment while JX is active I always get Jodel FC without any stacktrace. Only thing I could log is WIN DEATH with Jodel MainActivity. I thought the issue would be related to the RemoveBlurFromImages as stated in one of the other issue reports, but once I disabled that feature, I still got the same while seeing the blur in images. I build the apk myself from latest sources.

**Comment by Unbrick** [comment]
Hey MrYawnie,

we are currently updating JX for the latest Jodel version but i'm running in some bugs. I'm trying to fix them asap and push a working version to the repo!

**Comment by MrYawnie** [comment]
Okay. What bugs remain? Also, would it be possible to have SettingsActivity for the module, in where one could enable/disable each feature on-the-fly? If one feature breaks the whole module when Jodel gets updated, one could simply disable the features that cause the crash. For example currently the user ID feature works, but not others, as it can't connect the servers (the up/downvote and comment crash).

On Feb 11, 2017 18:15, Unbrick <notifications@github.com> wrote:

Hey MrYawnie,

we are currently updating JX for the latest Jodel version but i'm running sadly in some bugs. I'm trying to fix them asap and push a working version to the repo!

**Comment by Unbrick** [comment]
Jodel wont make any network requests anymore (the thing you call up/downvote and comment crash). And until now i'm not able to figure out why.

Adding the on-the-fly enabling/disabling of features would need a restructuring of JX but that might be a idea.

**Comment by MrYawnie** [comment]
Yes, I am aware it would require restructuring the whole model. The benefit, however, would be easier debugging in the future, as features could be tested individually, and issues found more easily. Also, it would enable the user to keep using the working features by disabling features that cause issues. Hypothetically.

**Comment by Unbrick** [comment]
Just pushed a working version to the repo, does your bug still occurr?

**Comment by MrYawnie** [comment]
I get this when trying to compile, causing the build to fail.
`:app:compileDebugKotlin
e: C:\Users\Jani\Desktop\Android Studio Projects\JodelXposed\app\src\main\java\com\jodelXposed\utils\Hooks.kt: (111, 34): Too many arguments for public constructor RemoveBlurFromImages() defined in com.jodelXposed.hooks.RemoveBlurFromImages

 FAILED
`

I deleted lines 109-116 from Hooks.kt (below) and was able to finish the build. I had to do it yesterday also. However, i still have the original issue. I can now see the new button that takes you to bottom of jodel comments, and it works, but I can't comment. So still issue with network requests.
` try {
            Log.xlog("#### Loading RemoveBlurFromImages hooks ####")
            RemoveBlurFromImages(lpparam)
            Log.xlog("#### Loading RemoveBlurFromImages hooks loaded! ####")
        } catch (e: Throwable) {
            e.printStackTrace()
            Log.xlog("!!!! FAILED loading RemoveBlurFromImages hooks! !!!!\n\n")
        }`

**Comment by MrYawnie** [comment]
Looks like it's an issue with my OP3, not the app. Got it working with my old S4 just fine.

**Comment by MrYawnie** [comment]
Just haven't been able to find out why it FC with my OP3..

**Comment by krokofant** [comment]
@MrYawnie Which rom and version are you one?

**Comment by MrYawnie** [comment]
Official OP3 OxygenOS 3.2.8 with November security patch (shouldn't have anything to do with it though 🤔). Latest Magisk + xposed v87.

**Comment by krokofant** [comment]
I had some crashes related to view inflation which only affected my OP3 OxygenOS 3.2.7 setup. On the latest Marshmallow based beta it worked fine though.

**Comment by MrYawnie** [comment]
Interesting. I'll probably try that tomorrow then. Thanks! 😊

**Comment by MrYawnie** [comment]
Works well so far! Only issue with adding pic from gallery. I made another issue report with the info, although you're probably already aware of it. Thanks!

**Comment by Keagel** [comment]
Compiled the APK with the latest sources and it still force closes on my Galaxy S6 when trying to comment/post (XtreStoLite ROM, Magisk v11.1, xposed v87 - all systemless)

**Comment by MrYawnie** [comment]
Either rom issue or Magisk issue. I had same issue with my OP3 using Magisk v11 and xposed v87. Downgraded and am now using latest supersu + systemless xposed v86.2 and works a treat.

**Comment by Keagel** [comment]
I can't really downgrade and use supersu since it seems to be detected by other applications even with Magisk. I guess I'll have to stick with normal Jodel until it's fixed

**Comment by MrYawnie** [comment]
I said it might be due to fw/rom or Magisk. I didn't explore more. Try another rom based on another few version.

**Comment by Keagel** [comment]
It works on my tablet with supersu and xposed v86.1, Cyanogen rom. Still doesn't on my phone with XtreStoLite, Magisk v11.1 and Xposed v87 though.
