### ISSUE TITLE
Jodel crashes when trying to comment/post with JodelXposed enabled

### ISSUE THREAD

**Issue by Hawpe** [krokofant/JodelXposed#62]
Tried with the past 3 JodelXposed versions, even compiled the sources myself in case they'd be more recent and nothing works.
I'm using a Galaxy S6 with Magisk v11.1, MagiskSU and xposed v87, all systemless. No error in the xposed logs. Nothing in logcat except "Win death".

**Comment by krokofant** [comment]
What rom are you using?

**Comment by Hawpe** [comment]
Currently using the latest XtreStoLite rom for the Galaxy S6, sorry forgot to mention it

**Comment by schoftwaer** [comment]
Same here, I'm using a OnePlus 2 with OxygenOS 3.1.0 (Android 6.0.1) installed. Xposed 86.2 systemless and Magisk 11.1 with MagsikSU.
I attached log from Jodel if it helps. :)
[Log_JodelApp.txt](https://github.com/krokofant/JodelXposed/files/819666/Log_JodelApp.txt)

**Comment by Unbrick** [comment]
@schoftwaer 
Please try using the latest JX version, we are currently messing around with the Anti-Anti-Xposed code to bring it to work on all architectures (due to native hooking). Hopefully the latest (2.4.4) works for you, if it doesent, please report back here!

**Comment by schoftwaer** [comment]
@Unbrick 
Thanks for the fast reply, I'm currently using 2.4.4 and catched the Log with this version. Also, I tried to completely reinstall both apps but no success here.
Please let me know if you need more information!

**Comment by Unbrick** [comment]
Sounds pretty weired. Also i can't see any exceptions in the crashlog and looks somehow incomplete. Could you try to give us a log using Android Studio / logcat?

**Comment by schoftwaer** [comment]
Okay, sorry I don't do that often. I made a new one, hopefully there is everything in it you need, assuredly there is more in it :D 
[Log_2017-03-05_21-37-37.txt](https://github.com/krokofant/JodelXposed/files/819730/Log_2017-03-05_21-37-37.txt)

**Comment by Unbrick** [comment]
Looks way better, give me a few minutes to dig into this.

**Comment by Unbrick** [comment]
@schoftwaer 
So i'm remembering simmilar errors @krokofant  encountered. (Reference: https://github.com/rovo89/Xposed/issues/202)

Xposed seem to be a litle bit buggy on custom roms on OnePlus devices. Do you have any rom updates available? If yes, would you mind updating?

**Comment by schoftwaer** [comment]
@Unbrick 
yeah, for sure. I can just take a Nandroid Backup and flash a CM13 based ROM to test it and report back here. Give me some minutes ;)

**Comment by ChavezD** [comment]
Hi there, i've got the same failure recently on the latest jodel/jodel xposed combo. 
I've tried to do a log, hope everything is fine and you can look into that - it is actually the first time for me over here on github and also my first log. :D 
I switched over to Jodel, wanted to post something - crash and than reopened it 2 times i think (if that matters)
[alogcat.2017-03-05-22-37-22+0100.txt](https://github.com/krokofant/JodelXposed/files/819773/alogcat.2017-03-05-22-37-22.0100.txt)

Edit: My device is a Huawei P8 with the following custom rom: https://forum.xda-developers.com/huawei-p8/development/rom-huawei-p8-arrow-custom-rom-based-t3561615
(Magisk 11.1 , MagiskSU, Systemless Xposed87.1)

**Comment by Unbrick** [comment]
@ChavezD 
In your case something in the layout hooks seem to be faulty. 

Are you running on Jodel 4.35.6 and JX 2.4.4? The version information in your logcat has been cut off.

**Comment by ChavezD** [comment]
Yes exactly, did a lot of updates (and testing) with Jodel xposed today, but the crashing already appeared with JX2.4.2. I think it began after updating jodel to 4.35.6. Even reinstalling one of them or both or clearing data didn't solve it

**Comment by Unbrick** [comment]
@ChavezD 
Some more questions for you:

- Which phone are you using?
- Which rom are you running on?
- Have you tried restarting (dumb question, i know but this is often a issue)?
- Which xposed version are you using?

**Comment by ChavezD** [comment]
@Unbrick Look at my first post, i've edited those things over there. (Magisk 11.1 , MagiskSU, Systemless xposed 87.1, Arrow Rom on huawei P8).
I did actually a lot of restarts and also force-closed jodel etc before i did a restart, if that even changes everything (im really not into that)

**Comment by schoftwaer** [comment]
@Unbrick 
So, I tested JX 2.4.4 now on ResurrectionRemix Rom (also Android 6.0.1) and everything is working fine now!
Thank you for pointing out the OxygenOS issue :)

**Comment by Unbrick** [comment]
@schoftwaer 
Thanks for your response! I'll add that to the readme!

@ChavezD 
Somethin in your system is quite interesting. Seems like you have a different View.class/ViewGroup.class .
Its quite hard to do something for us, as for example the CreateTextPostFragment#onCreateView does not return View.class in your case (which it actually should on any Android rom). Have you tried a different rom?

**Comment by ChavezD** [comment]
Actually i didn't try any other rom, since this is the only custom rom available for my device (god damn i'll never again buy any huawei phone with their damn kirin cpu and not public sourcecodes).
Maybe i'm gonna flash a new(old) rom soon, but on the other hand my new phone (finally htc again) will arrive during the next week, so I don't want to spend much time over here if you know what i mean. 
Eventually i'm gonna contact the rom developer anyhow to figure out the problems you have mentioned. Any ideas what i should point out to him?
What so ever, all of you guys are doing a great job, I really appreciate it!

**Comment by Unbrick** [comment]
@ChavezD 
In your case i assume xposed won't be 100% compatible with your phone (as other apps with usual resources work). So this COULD be realated to the XResources.class implementation. But honestly i don't have any clue. Once you receive your new phone and install JodelXposed again, could you report back whether it works? And thank you very much for the praise!

I'm closing this now as we already have three issues in this one. But you still can comment!

**Comment by Hawpe** [comment]
Still doesn't work with the latest version of JX, still on XtreStoLite. The logcat now shows a lot more errors from JX (before it only logged "Win death" when the app would crash).
[alogcat.2017-03-06-18-40-51+0100.txt](https://github.com/krokofant/JodelXposed/files/821977/alogcat.2017-03-06-18-40-51.0100.txt)

**Comment by Hawpe** [comment]
Tried with another ROM (OdexLite) and Jodel crashes with it too

**Comment by Unbrick** [comment]
@Hawpe

Which Android version is your ROM on?
Which Xposed version are you using? 
Which Jodel and JX version are you using?
Can you provide a stacktrace from only Jodel?

**Comment by Hawpe** [comment]
Using Android 6.0.1, latest XtreStoLite ROM for the Galaxy S6 along with Xposed v87 systemless by topjohnwu, Magisk v11.1 and MagiskSU systemless.
Latest Jodel version from the Play Store and JX 2.4.4 from the xposed repo.

Are these the logs you need?

[xposed_error_20170307_090126.txt](https://github.com/krokofant/JodelXposed/files/823714/xposed_error_20170307_090126.txt)
[alogcat.2017-03-07-08-59-53+0100.txt](https://github.com/krokofant/JodelXposed/files/823716/alogcat.2017-03-07-08-59-53.0100.txt)

**Comment by Unbrick** [comment]
@Hawpe 
Your setup looks fine so far, xposed is loading without any problems. But i can't find any crash except for the WIN DEATH...but this could point to anything. Most probably to a memory leak but i'm not aware that JodelXposed would have one.

**Comment by Keagel** [comment]
Crashing for me too. Absolutely everything works except commenting/posting. The crash only happens when I click the "+" on a post or on the home screen. The same WIN DEATH error shows up on the OdexLite ROM (just tried to install it too)

**Comment by Unbrick** [comment]
@Keagel / @Hawpe 
I now compiled a new apk avoiding layout inflation (and updated to the latest Jodel version). I've uploaded it to the Xposed repo. Give it a shot.

**Comment by ChavezD** [comment]
@Unbrick for me the Update is working, Can now comment again. But the answer counter #1, #2 and so on is gone, as well as the Button to go to top/bottom is wrong. It now is colored as the Jodel itself and doesn't Display the arrow anymore. Clicking it does nothing

**Comment by Keagel** [comment]
Update is working here too for comments/posts but now clicking "change location" in the JX settings makes the app crash. Sorry for all the bug reports!

Edit: Trying to pick the color (most right icon when you create a new post) makes it crash too

[alogcat.2017-03-09-07-15-32+0100.txt](https://github.com/krokofant/JodelXposed/files/829993/alogcat.2017-03-09-07-15-32.0100.txt)
[xposed_error_20170309_071625.txt](https://github.com/krokofant/JodelXposed/files/831911/xposed_error_20170309_071625.txt)

**Comment by Unbrick** [comment]
@Keagel 
As i thought your Xposed doesen't like layout inflation. I replaced the layout inflation in the CreateTextPostFragment with a `new AppCompatImageView(ctx);` . This one works for you but for some other people this one crashes. The color picker still works with layout inflation so it crashes when opening. 

As your log points out you are also using a "old" Jodel version:
`03-09 07:15:05.741 I/Xposed  (16589): JodelTarget 4.36.0 (1000600)
03-09 07:15:05.741 I/Xposed  (16589): JodelLocal 4.35.6 (1000506)`

Please consider upgrading to 4.36.0 and report all not working functions again. I guess the change location crash is issued by the old version.


@ChavezD 
krokofant encountered simmilar issues. They disappeared somehow, nobody knows why. Could you provide a screenshot from the buggy FastScrollDownButton and maybe a new logcat? Sorry to ask this all the time but solving the issue without one could get very difficult.

**Comment by Keagel** [comment]
I upgraded to the latest Jodel version right after the logs and the two bugs I reported were still occurring. The problems @ChavezD reported were happening to me too on the 4.35.6 version but were fixed once I updated to 4.36.0 though

**Comment by Unbrick** [comment]
@Keagel 
I tried to fix both of them now, changed some version numbers and instantiating the color picker now programatically. Could you give it a try before i push a release?

[jx_test.zip](https://github.com/krokofant/JodelXposed/files/836160/jx_test.zip)

**Comment by Keagel** [comment]
@Unbrick fixed the "change location" crash but now the color picker/upload image from gallery are gone (not crashing, just not appearing when creating a new post)

**Comment by Unbrick** [comment]
Whoa. Very weired, i didn't change a bit in there. I'm sorry to ask but could you provide a log for me?

**Comment by Keagel** [comment]
Sure thing. There's a shitload of errors in the xposed log:

[xposed_error_20170311_232450.txt](https://github.com/krokofant/JodelXposed/files/836166/xposed_error_20170311_232450.txt)
[alogcat.2017-03-11-23-24-59+0100.txt](https://github.com/krokofant/JodelXposed/files/836167/alogcat.2017-03-11-23-24-59.0100.txt)

**Comment by schoftwaer** [comment]
@Unbrick
Testet it also because Change Location crashed also for me since 2.4.5!
Everything is working now, so unfortunately I can't help with that issue...

**Comment by Unbrick** [comment]
@Keagel 
Your log looks quite interesting. JodelXposed isn't able to find the resources...did you do a reboot? :D

@schoftwaer 
Thank you very much for testing! So finally no issues for you anymore :)

**Comment by Keagel** [comment]
I had done a soft reboot but I guess it wasn't enough. Did a full reboot and it works now :)

**Comment by Unbrick** [comment]
@Keagel 
Awsome, thank you! Seems to be ready to release a new version soon! I'll check whether its running on @krokofant's device (he has a OP3, they are very sensitive) and make a release afterwards.

Thank you all very much for the bug reports! I'll close this issue now as its getting quite long. If you encounter any new bugs you are welcome to report them in a new issue!
