### ISSUE TITLE
Fix track poster hooks

### ISSUE THREAD

**Issue by Unbrick** [krokofant/JodelXposed#66]
Seems like the "Track poster" (numbers behind comments) was disabled serversided by the Jodel developers by changing the API-response.

Previously it contained a user handle, now it only differs between "OJ" and "replier".

**Comment by Hehe55** [comment]
Did you just fix it niw?  I all of the sudden got a track poster  but no idea if it's from you guys or from the Jodel devs.  Using jx 2.4.7 and Jodel 4.40.apk.

**Comment by Hehe55** [comment]
Using Jodel 4.40.1**

**Comment by Unbrick** [comment]
Closed as jodel implemented the TrackPosters feature by theirselves
