### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by ziadpq** [krokofant/JodelXposed#69]
i just find out about this beutifull xposed module 
and none one the buttons work ):

jodel version 4.43.1

**Comment by ziadpq** [comment]
and i just find out that reply button not there 🤕

**Comment by Unbrick** [comment]
I uploaded a new version (2.5.0). Try this one!

**Comment by ziadpq** [comment]
wow that was fast thank u 
/
the replay button did come back but still the . add photo from gallary. button dont work
and the map thing in the jodel camera gone

**Comment by Unbrick** [comment]
Try installing another gallery application like the [Google Photos app](https://play.google.com/store/apps/details?id=com.google.android.apps.photos). Use this to choose your image from the gallery. 

I dont really get what you mean with the mal thing in the jodel camera...

**Comment by ziadpq** [comment]
nvm what i said about the change location in jodel camera
and i did try gallery apps but all apps dont work cz jodel dont ask for camera 
that the 2 buttons that dont work .gallary .. color..
http://imgur.com/a/HERky
take ur time fixing 😄 ❤️ 
sorry my eng is bad

**Comment by Unbrick** [comment]
If your speaking german, lets switch over to german (my native languange) but i honestly don't really get where you encounter a problem. Won't the Color/Gallery picker buttons react on pressing?

**Comment by ziadpq** [comment]
actually nothing work with me from ur xposed module  ):
idk why

**Comment by ziadpq** [comment]
im not german im saudi ^^
buttons dont no nothing at all

**Comment by Unbrick** [comment]
Ensure that you are on the Jodel version 4.43.1 and the JodelXposed version 2.5.0 . Then clear the app data of both of them, restart your mobile phone and try again!

**Comment by ziadpq** [comment]
thank u it worked 😍
